# Deploy workflow

name: Deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:  
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Create the ssh directory
        run: mkdir ~/.ssh && chmod 700 ~/.ssh

      - name: Install the deploy key
        run: 'echo "$SSH_KEY" > ~/.ssh/deploy'
        shell: bash
        env:
          SSH_KEY: ${{ secrets.DEPLOY_KEY }}
        
      - name: Check the deploy key
        run: cat ~/.ssh/deploy
        
      - name: Install the known hosts
        run: 'echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts'

      - name: Deploy code
        run: ssh -i ~/.ssh/deploy phil@pantoniotti.com
    
    
